#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/init_tempmon
NAME=init_tempmon
DESC="temperature monitor daemon"

MNTPOINT=/mnt/mmc
MMCDEV=/dev/mmcblk0p1
SOME_SCRIPT=init_tempmon.py

case "$1" in
  start)
	echo -n "Starting $DESC: "
	if [ -f $MNTPOINT/$SOME_SCRIPT ]; then
	    echo "    Launching $SOME_SCRIPT"
	    $MNTPOINT/$SOME_SCRIPT
	else
	    echo "    $SOME_SCRIPT not found. Nothing to launch."
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	echo "$NAME."
	;;
  restart)
	echo -n "Restarting $DESC: "
	echo "$NAME."
	;;
  status)
	echo -n "$NAME status:"
	if [ -f /var/run/$NAME ]; then
	  echo -n "Running"
	else
	  echo -n "Not running"
	fi
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|status}" >&2
	exit 1
	;;
esac

exit 0 
